### ISSUE TITLE
Under high load the litmus:install_agent fails with a timeout

### ISSUE THREAD

**Issue by hajee** [puppetlabs/puppet_litmus#161]
When using litmus on a docker machine under high load (many running jobs) a timeout is reported. Is there way in general to influence this timeout?

```
$ bundle exec rake "litmus:install_agent"
install_agent
From git://github.com/puppetlabs/puppetlabs-facts
 * [new tag]         0.1.0      -> 0.1.0
 * [new tag]         0.1.1      -> 0.1.1
 * [new tag]         0.1.2      -> 0.1.2
 * [new tag]         0.2.0      -> 0.2.0
 * [new tag]         0.3.0      -> 0.3.0
 * [new tag]         0.3.1      -> 0.3.1
 * [new tag]         0.4.0      -> 0.4.0
 * [new tag]         0.4.1      -> 0.4.1
 * [new tag]         0.5.0      -> 0.5.0
 * [new tag]         0.5.1      -> 0.5.1
From git://github.com/puppetlabs/puppetlabs-puppet_agent
 * [new tag]         0.1.0      -> 0.1.0
 * [new tag]         0.2.0      -> 0.2.0
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
rake aborted!
Failed on 67747dab9676dc0bc3f140d38d120ab6c78657e39b810342d5cf1a29c3a20644
{"node"=>"67747dab9676dc0bc3f140d38d120ab6c78657e39b810342d5cf1a29c3a20644", "target"=>"67747dab9676dc0bc3f140d38d120ab6c78657e39b810342d5cf1a29c3a20644", "action"=>nil, "object"=>nil, "status"=>"failure", "result"=>{"_error"=>{"kind"=>"puppetlabs.tasks/exception-error", "issue_code"=>"EXCEPTION", "msg"=>"read timeout reached", "details"=>{"class"=>"Docker::Error::TimeoutError", "stack_trace"=>"/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/docker-api-1.34.2/lib/docker/connection.rb:52:in `rescue in request'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/docker-api-1.34.2/lib/docker/connection.rb:37:in `request'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/docker-api-1.34.2/lib/docker/exec.rb:73:in `start!'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/docker-api-1.34.2/lib/docker/container.rb:92:in `exec'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker/connection.rb:41:in `execute'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker.rb:122:in `block (2 levels) in run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker/connection.rb:90:in `with_remote_tempdir'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker.rb:99:in `block in run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker.rb:35:in `with_connection'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/docker.rb:96:in `run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/base.rb:129:in `block in batch_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/base.rb:71:in `with_events'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/transport/base.rb:127:in `batch_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/executor.rb:263:in `block (3 levels) in run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/executor.rb:224:in `with_node_logging'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/executor.rb:262:in `block (2 levels) in run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/bolt-1.26.0/lib/bolt/executor.rb:100:in `block (3 levels) in queue_execute'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'\\n/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"}}}}
try running 'bolt task run puppet_agent::install --targets 67747dab9676dc0bc3f140d38d120ab6c78657e39b810342d5cf1a29c3a20644 --inventoryfile inventory.yaml --modulepath /builds/enterprisemodules/ora_config/spec/fixtures/modules'
/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/bundler/gems/puppet_litmus-28d74531efe5/lib/puppet_litmus/rake_tasks.rb:187:in `block (3 levels) in <top (required)>'
/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/bundler/gems/puppet_litmus-28d74531efe5/lib/puppet_litmus/rake_tasks.rb:184:in `each'
/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/bundler/gems/puppet_litmus-28d74531efe5/lib/puppet_litmus/rake_tasks.rb:184:in `block (2 levels) in <top (required)>'
/builds/enterprisemodules/ora_config/cache/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => litmus:install_agent
(See full trace by running task with --trace)

```

**Comment by hajee** [comment]
My guess is that the root cause is bolt:

```
bolt command run 'sleep 300' --targets 94651c0997cbc03a40d1955dcb158dec3e588c88cb6d94d3e0ab6491a070616d -i inventory.yaml
```
By the way, this also happens on apply_manifest calls that take long(er)

So the issue becomes how can we pass a (longer) timeout from the litmus api through bolt to docker.

**Comment by tphoney** [comment]
does setting this https://puppet.com/docs/bolt/latest/bolt_command_reference.html#transport-options help ? For the last example ? if it does we can do something about it

**Comment by hajee** [comment]
No, unfortunately, it doesn't. But after this [PR](https://github.com/puppetlabs/bolt/pull/1089) is merged, it will. I'll close the issue here.
