### ISSUE TITLE
Access to bolt > 3.0 for Terraform integration

### ISSUE THREAD

**Issue by shaun-rutherford** [puppetlabs/puppet_litmus#408]
Greetings Everyone,

I'm trying to leverage Bolt's Terraform inventory provider for use in our Puppet_Litmus testing.
https://forge.puppet.com/modules/puppetlabs/terraform

This works no issue when using bolt directly from my OS install:
```
bolt --version
3.7.0

bolt task run puppet_agent::install -i inventory.yaml --targets cloud-webs --run-as root
```
However, when using pdk bundle exec commands to leverage puppet_litmus rake tasks, it tries to use bolt 2.44.0 and apparently that version of the gem doesn't know what the Terraform provider is:

```
pdk bundle exec rake litmus:install_agent
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.21.1
install_agent
rake aborted!
Bolt::Plugin::PluginError::Unknown: Unknown plugin: 'terraform'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:229:in `get_hook'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:309:in `resolve_single_reference'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:287:in `resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `block in resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `flat_map'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:52:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `block in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `map'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/inventory.rb:24:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/inventory.rb:24:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory.rb:113:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory.rb:113:in `create_version'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:170:in `inventory'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:195:in `run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:26:in `block in run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:152:in `block in with_runner'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:150:in `with_runner'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:25:in `run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_helper.rb:225:in `block in install_agent'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_helper.rb:210:in `install_agent'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_tasks.rb:126:in `block (2 levels) in <top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `<main>'
Tasks: TOP => litmus:install_agent
(See full trace by running task with --trace)
```

Is there a proper way to update the PDK to use a newer version of Bolt and if not do we have an ETA of when a newer version will be available in the PDK?

Many thanks,

**Comment by DavidS** [comment]
This is already fixed in https://github.com/puppetlabs/puppet_litmus/pull/407 and will soon be released in puppet_litmus.

**Comment by pmcmaw** [comment]
Hey @shaun-rutherford 

I would just like to let you know that litmus v0.27.0 has now been released and is available on Rubygems. It contains a fix for your issue. :-)

**Comment by shaun-rutherford** [comment]
Good Morning @pmcmaw 
Thanks for the notice and quick turn around.

I updated my gem list for puppet_litmus to 0.27.0:
```
gem list | grep puppet_litmus
puppet_litmus (0.27.0, 0.26.4, 0.26.3, 0.26.0, 0.23.1)
```
However, puppet PDK still attempts to use Bolt 2.44.0:
```
pdk bundle exec rake litmus:install_agent
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.21.1
install_agent
rake aborted!
Bolt::Plugin::PluginError::Unknown: Unknown plugin: 'terraform'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:229:in `get_hook'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:309:in `resolve_single_reference'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:287:in `resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `block in resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `flat_map'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/plugin.rb:282:in `resolve_top_level_references'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:52:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `block in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `map'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/group.rb:84:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/inventory.rb:24:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory/inventory.rb:24:in `initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory.rb:113:in `new'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt/inventory.rb:113:in `create_version'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:170:in `inventory'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:195:in `run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:26:in `block in run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:152:in `block in with_runner'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:150:in `with_runner'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bolt-2.44.0/lib/bolt_spec/run.rb:25:in `run_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_helper.rb:225:in `block in install_agent'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_helper.rb:210:in `install_agent'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_tasks.rb:126:in `block (2 levels) in <top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `<main>'
Tasks: TOP => litmus:install_agent
(See full trace by running task with --trace)
```

Is their a way to tell the puppet PDK to use the newer version of bolt on my system?

**Comment by pmcmaw** [comment]
Browsing in the logs, it looks like it may still be using an older version of litmus:

`/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_helper.rb:210:in `install_agent'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet_litmus-0.26.0/lib/puppet_litmus/rake_tasks.rb:126:in `block (2 levels) in <top (required)>'`

Your environment doesn't seem to be using the latest version of litmus yet, I hope this helps.
