### ISSUE TITLE
Problems provisioning Debian-based containers

### ISSUE THREAD

**Issue by LukasAud** [puppetlabs/puppet_litmus#442]
## Describe the Bug
Litmus has problems provisioning Debian environments, particularly when working with litmusimages.

## Expected Behavior
When using litmus to provision an environment using a Debian litmusimage, it should work.

## Steps to Reproduce
1. Go to any module (latest test was on puppetlabs/mysql)
2. Run `bundle install`
3. Run `bundle exec rake 'litmus:provision[provision::docker, litmusimage/debian:9]'`

## Environment
 - puppet_litmus v0.32.0
 - Debian 9, 10 and 11

## Additional Context
Most common error message:
```
Results:
  localhost: {"_error"=>{"kind"=>"provision/docker_failure", "msg"=>"Attempted to run\ncommand:'docker exec litmusimage_debian_9-52921 service ssh restart'\nstdout:\nstderr:Failed to connect to bus: No such file or directory\nFailed to connect to bus: No such file or directory\n", "backtrace"=>["/private/tmp/0f454106-8476-49a8-8a1f-fdab557adf63/provision/lib/task_helper.rb:21:in `run_local_command'", "/tmp/0f454106-8476-49a8-8a1f-fdab557adf63/provision/tasks/docker.rb:64:in `fix_ssh'", "/tmp/0f454106-8476-49a8-8a1f-fdab557adf63/provision/tasks/docker.rb:192:in `provision'", "/tmp/0f454106-8476-49a8-8a1f-fdab557adf63/provision/tasks/docker.rb:232:in `<main>'"], "details"=>{}}}}
/Users/lukas.audzevicius/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
/Users/lukas.audzevicius/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
Tasks: TOP => litmus:provision
```
It is speculated to have to do with one of the latest releases of docker back in January-February 2022. Provisioning seems to be working on Github actions for the automated testing. This is issue is likely to be tied to docker desktop, and therefore, mostly a local-level issue.

**Comment by LukasAud** [comment]
Closing this issue as it seems to not be relevant anymore and it looks like it was already addressed at some point.
